# Generated by Django 5.1.1 on 2024-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelapp", "0002_usersubmits"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserClientInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phonenumber", models.CharField(max_length=15)),
                ("investigate_date", models.DateField(blank=True, null=True)),
                ("schedule_date", models.DateField(blank=True, null=True)),
                ("lead", models.CharField(blank=True, max_length=255, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("assigned_user", models.CharField(max_length=255)),
            ],
        ),
    ]
