# Generated by Django 5.1.1 on 2024-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panelapp", "0004_clientdata_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdata",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientdata",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userclientinteraction",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userclientinteraction",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubmits",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubmits",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
